default: &default
  adapter: mysql2
  username: saml_app
  password: password
  host: 127.0.0.1
  pool: 5
  timeout: 5000
  encoding: utf8
  collation: utf8_bin

development:
  <<: *default
  database: saml_development

test:
  <<: *default
  database: saml_test

production:
  <<: *default
  username: <%= ENV['SAML_DB_USERNAME'] %>
  password: <%= ENV['SAML_DB_PASSWORD'] %>
  database: <%= ENV['SAML_DB_NAME'] %>
  host: <%= ENV['SAML_DB_HOST'] %>
  port: <%= ENV['SAML_DB_PORT'] %>
